const cn = {
  0: "Russian Federation",
  1: "Ukraine",
  2: "Kazakhstan",
  3: "China",
  4: "Philippines",
  5: "Myanmar",
  6: "Indonesia",
  7: "Malaysia",
  8: "Kenya",
  9: "Tanzania",
  10: "Vietnam",
  11: "Kyrgyzstan",
  12: "United States virt",
  13: "Israel",
  14: "HongKong",
  15: "Poland",
  16: "England (Great Britain)",
  17: "Madagascar",
  18: "DR Congo",
  19: "Nigeria",
  20: "Macao",
  21: "Egypt",
  22: "India",
  23: "Ireland",
  24: "Cambodia",
  25: "Lao People's",
  26: "Haiti",
  27: "Ivory Coast",
  28: "Gambia",
  29: "Serbia",
  30: "Yemen",
  31: "South Africa",
  32: "Romania",
  33: "Colombia",
  34: "Estonia",
  35: "Azerbaijan",
  36: "Canada",
  37: "Morocco",
  38: "Ghana",
  39: "Argentinas",
  40: "Uzbekistan",
  41: "Cameroon",
  42: "Chad",
  43: "Germany",
  44: "Lithuania",
  45: "Croatia",
  46: "Sweden",
  47: "Iraq",
  48: "Netherlands",
  49: "Latvia",
  50: "Austria",
  51: "Belarus",
  52: "Thailand",
  53: "Saudi Arabia",
  54: "Mexico",
  55: "Taiwan",
  56: "Spain",
  58: "Algeria",
  59: "Slovenia",
  60: "Bangladesh",
  61: "Senegal",
  62: "Turkey",
  63: "Czech Republic",
  64: "Sri Lanka",
  65: "Peru",
  66: "Pakistan",
  67: "New Zealand",
  68: "Guinea",
  69: "Mali",
  70: "Venezuela",
  71: "Ethiopia",
  72: "Mongolia",
  73: "Brazil",
  74: "Afghanistan",
  75: "Uganda",
  76: "Angola",
  77: "Cyprus",
  78: "France",
  79: "Papua new Guinea",
  80: "Mozambique",
  81: "Nepal",
  82: "Belgium",
  83: "Bulgaria",
  84: "Hungary",
  85: "Moldova, Republic of",
  86: "Italy",
  87: "Paraguay",
  88: "Honduras",
  89: "Tunisia",
  90: "Nicaragua",
  91: "Timor-Leste",
  92: "Bolivia",
  93: "Costa Rica",
  94: "Guatemala",
  95: "United Arab Emirates",
  96: "Zimbabwe",
  97: "Puerto Rico",
  99: "Togo",
  100: "Kuwait",
  101: "El Salvador",
  102: "Libya",
  103: "Jamaica",
  104: "Trinidad and Tobago",
  105: "Ecuador",
  106: "Swaziland",
  107: "Oman",
  108: "Bosnia and Herzegovina",
  109: "Dominican Republic",
  111: "Qatar",
  112: "Panama",
  114: "Mauritania",
  115: "Sierra Leone",
  116: "Jordan",
  117: "Portugal",
  118: "Barbados",
  119: "Burundi",
  120: "Benin",
  121: "Brunei Darussalam",
  122: "Bahamas",
  123: "Botswana",
  124: "Belize",
  125: "Central African Republic",
  126: "Dominica",
  127: "Grenada",
  128: "Georgia",
  129: "Greece",
  130: "Guinea-Bissau",
  131: "Guyana",
  132: "Iceland",
  133: "Comoros",
  134: "Saint Kitts and Nevis",
  135: "Liberia",
  136: "Lesotho",
  137: "Malawi",
  138: "Namibia",
  139: "Niger",
  140: "Rwanda",
  141: "Slovakia",
  142: "Suriname",
  143: "Tajikistan",
  144: "Monaco",
  145: "Bahrain",
  146: "Reunion",
  147: "Zambia",
  148: "Armenia",
  149: "Somalia",
  150: "Republic of the Congo",
  151: "Chile",
  152: "Burina Faso",
  153: "Lebanon",
  154: "Gabon",
  155: "Albania",
  156: "Uruguay",
  157: "Mauritius",
  158: "Bhutan",
  159: "Maldives",
  160: "Guadeloupe",
  161: "Turkmenistan",
  162: "French Guiana",
  163: "Finland",
  164: "Saint Lucia",
  165: "Luxembourg",
  166: "Saint Vincent",
  167: "Equatorial Guinea",
  168: "Djibouti",
  169: "Antigua and Barbuda",
  170: "Cayman Islands",
  171: "Montenegro",
  172: "Denmark",
  173: "Switzerland",
  174: "Norway",
  175: "Australia",
  176: "Eritrea",
  177: "South Sudan",
  178: "Sao Tome and Principe",
  179: "Aruba",

  180: "Montserrat",
  181: "Anguilla",
  182: "Japan",
  183: "North Macedonia",
  184: "Seychelles",
  185: "New Caledonia",
  186: "Cape Verde",
  187: "United States",
  10016: "Iran",
  10227: "Tonga",
  10231: "Samoa",
  10348: "Liechtenstein",
  10349: "Sint Maarten",
  10350: "South Korea",
  10351: "Singapore",
};

const countryCodes = {
  Afghanistan: 74,
  Albania: 155,
  Algeria: 58,
  Angola: 76,
  Anguilla: 181,
  "Antigua and Barbuda": 169,
  Argentinas: 39,
  Armenia: 148,
  Aruba: 179,
  Australia: 175,
  Austria: 50,
  Azerbaijan: 35,
  Bahamas: 122,
  Bahrain: 145,
  Bangladesh: 60,
  Barbados: 118,
  Belarus: 51,
  Belgium: 82,
  Belize: 124,
  Benin: 120,
  Bhutan: 158,
  Bolivia: 92,
  "Bosnia and Herzegovina": 108,
  Botswana: 123,
  Brazil: 73,
  "Brunei Darussalam": 121,
  Bulgaria: 83,
  "Burina Faso": 152,
  Burundi: 119,
  Cambodia: 24,
  Cameroon: 41,
  Canada: 36,
  "Cape Verde": 186,
  "Cayman Islands": 170,
  "Central African Republic": 125,
  Chad: 42,
  Chile: 151,
  China: 3,
  Colombia: 33,
  Comoros: 133,
  "Costa Rica": 93,
  Croatia: 45,
  Cyprus: 77,
  "Czech Republic": 63,
  Denmark: 172,
  Djibouti: 168,
  Dominica: 126,
  "Dominican Republic": 109,
  "DR Congo": 18,
  Ecuador: 105,
  Egypt: 21,
  "El Salvador": 101,
  "England (Great Britain)": 16,
  "Equatorial Guinea": 167,
  Eritrea: 176,
  Estonia: 34,
  Ethiopia: 71,
  Finland: 163,
  France: 78,
  "French Guiana": 162,
  Gabon: 154,
  Gambia: 28,
  Georgia: 128,
  Germany: 43,
  Ghana: 38,
  Greece: 129,
  Grenada: 127,
  Guadeloupe: 160,
  Guatemala: 94,
  Guinea: 68,
  "Guinea-Bissau": 130,
  Guyana: 131,
  Haiti: 26,
  Honduras: 88,
  HongKong: 14,
  Hungary: 84,
  Iceland: 132,
  India: 22,
  Indonesia: 6,
  Iran: 10016,
  Iraq: 47,
  Ireland: 23,
  Israel: 13,
  Italy: 86,
  "Ivory Coast": 27,
  Jamaica: 103,
  Japan: 182,
  Jordan: 116,
  Kazakhstan: 2,
  Kenya: 8,
  Kuwait: 100,
  Kyrgyzstan: 11,
  "Lao People's": 25,
  Latvia: 49,
  Lebanon: 153,
  Lesotho: 136,
  Liberia: 135,
  Libya: 102,
  Liechtenstein: 10348,
  Lithuania: 44,
  Luxembourg: 165,
  Macao: 20,
  Madagascar: 17,
  Malawi: 137,
  Malaysia: 7,
  Maldives: 159,
  Mali: 69,
  Mauritania: 114,
  Mauritius: 157,
  Mexico: 54,
  "Moldova, Republic of": 85,
  Monaco: 144,
  Mongolia: 72,
  Montenegro: 171,
  Montserrat: 180,
  Morocco: 37,
  Mozambique: 80,
  Myanmar: 5,
  Namibia: 138,
  Nepal: 81,
  Netherlands: 48,
  "New Caledonia": 185,
  "New Zealand": 67,
  Nicaragua: 90,
  Niger: 139,
  Nigeria: 19,
  "North Macedonia": 183,
  Norway: 174,
  Oman: 107,
  Pakistan: 66,
  Panama: 112,
  "Papua new Guinea": 79,
  Paraguay: 87,
  Peru: 65,
  Philippines: 4,
  Poland: 15,
  Portugal: 117,
  "Puerto Rico": 97,
  Qatar: 111,
  "Republic of the Congo": 150,
  Reunion: 146,
  Romania: 32,
  "Russian Federation": 0,
  Rwanda: 140,
  "Saint Kitts and Nevis": 134,
  "Saint Lucia": 164,
  "Saint Vincent": 166,
  Samoa: 10231,
  "Sao Tome and Principe": 178,
  "Saudi Arabia": 53,
  Senegal: 61,
  Serbia: 29,
  Seychelles: 184,
  "Sierra Leone": 115,
  Singapore: 10351,
  "Sint Maarten": 10349,
  Slovakia: 141,
  Slovenia: 59,
  Somalia: 149,
  "South Africa": 31,
  "South Korea": 10350,
  "South Sudan": 177,
  Spain: 56,
  "Sri Lanka": 64,
  Suriname: 142,
  Swaziland: 106,
  Sweden: 46,
  Switzerland: 173,
  Taiwan: 55,
  Tajikistan: 143,
  Tanzania: 9,
  Thailand: 52,
  "Timor-Leste": 91,
  Togo: 99,
  Tonga: 10227,
  "Trinidad and Tobago": 104,
  Tunisia: 89,
  Turkey: 62,
  Turkmenistan: 161,
  Uganda: 75,
  Ukraine: 1,
  "United Arab Emirates": 95,
  "United States": 187,
  "United States virt": 12,
  Uruguay: 156,
  Uzbekistan: 40,
  Venezuela: 70,
  Vietnam: 10,
  Yemen: 30,
  Zambia: 147,
  Zimbabwe: 96,
};

const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentinas",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "DR Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "England (Great Britain)",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "French Guiana",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "HongKong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua new Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent",
  "Samoa",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United States",
  "United States virt",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const major = [
  "Russian Federation",
  "South Korea",
  "India",
  "United States",
  "China",
  "Philippines",
  "Australia",
  "Canada",
  "United Kingdom",
  "Germany",
  "Japan",
  "France",
];
module.exports = { countryCodes, countries, major };
