export const serviceCodes = {
  hn: "1688",
  wj: "1xbet",
  qi: "32red",
  hk: "4Fun",
  an: "Adidas",
  uk: "Airbnb",
  zl: "Airtel",
  bt: "Alfa",
  ab: "Alibaba",
  hx: "AliExpress",
  hw: "Alipay",
  yo: "Amasia",
  am: "Amazon",
  pm: "AOL",
  wx: "Apple",
  av: "avito",
  ff: "AVON",
  gr_bf: "Beanfun",
  ie: "bet365",
  vd: "Betfair",
  zu: "BigC",
  bl: "BIGO LIVE",
  zs: "Bilibili",
  lt: "BitClout",
  ua: "BlaBlaCar",
  bz: "Blizzard",
  tx: "Bolt",
  mo: "Bumble",
  ip: "Burger King",
  ls: "Careem",
  gr_rd: "Chalkboard",
  dd: "CloudChat",
  re: "Coinbase",
  wc: "Craigslist",
  ox: "Damejidlo",
  fr: "Dana",
  zk: "Deliveroo",
  zz: "Dent",
  os: "Dhani",
  xk: "DiDi",
  ds: "Discord",
  sd: "dodopizza",
  ak: "Douyu",
  ve: "Dream11",
  hz: "Drom",
  fi: "Dundle",
  rz: "EasyPay",
  dh: "eBay",
  gr_dh: "Ebay-kleinanzeigen",
  fb: "facebook",
  se: "Feeld",
  cn: "Fiverr",
  gr_fw: "Flowwow",
  nz: "Foodpanda",
  mv: "Fruitz",
  gr_fx: "Ftx",
  cg: "Gemgala",
  gr_gc: "Getcontact",
  ul: "Getir",
  gt: "Gett",
  jd: "GiraBank",
  bp: "GoFundMe",
  ni: "Gojek",
  go: "Google,youtube,Gmail",
  gf: "GoogleVoice",
  gr_gs: "Gorillas",
  gr_ed: "Gorodsreda",
  yw: "Grindr",
  xs: "GroupMe",
  gx: "Hepsiburadacom",
  en: "Hermes",
  ss: "Hezzl",
  vz: "Hinge",
  ks: "Hirect",
  jl: "Hopi",
  gr_hb: "Humble bundle",
  pd: "IFood",
  im: "Imo",
  gr_im: "IMO messager",
  ju: "Indomaret",
  ig: "Instagram",
  zo: "Kaggle",
  kt: "KakaoTalk",
  ol: "KazanExpress",
  bf: "Keybase",
  fz: "KFC",
  sq: "KuCoinPlay",
  vp: "Kwai",
  sb: "Lamoda",
  dl: "Lazada",
  do: "Leboncoin",
  xf: "LightChat",
  gr_lc: "LikeCentre",
  me: "Line messenger",
  tn: "LinkedIN",
  tu: "Lyft",
  ma: "Mail.ru",
  lb: "Mailru Group",
  fd: "Mamba, MeetMe",
  ry: "McDonalds",
  lv: "Megogo",
  dg: "Mercari",
  bv: "Metro",
  mc: "Michat",
  mm: "Microsoft",
  bg: "MIXMART",
  gy: "MIYACHAT",
  py: "Monese",
  bu: "MonobankIndia",
  da: "MTS CashBack",
  ae: "myGLO",
  nv: "Naver",
  nf: "Netflix",
  ew: "Nike",
  vm: "OkCupid",
  ly: "Olacabs",
  sn: "OLX",
  dr: "OpenAI",
  xh: "OVO",
  sg: "OZON",
  gg: "PagSmile",
  zr: "Papara",
  wo: "Parkplus",
  gr_pp: "ParlayPlay",
  ts: "PayPal",
  jq: "Paysafecard",
  at: "Perfluence",
  fx: "PGbonus",
  ev: "Picpay",
  ro: "PingCode",
  pf: "pof.com",
  oz: "Poshmark",
  po: "premium.one",
  cm: "Prom",
  dp: "ProtonMail",
  vf: "Q12 Trivia",
  cc: "Quipp",
  co: "Rediffmail",
  gr_re: "Remit",
  ij: "Revolut",
  mn: "RRSA",
  fl: "RummyLoot",
  gs: "Samsung",
  vv: "Seosprint",
  ka: "Shopee",
  gr_sg: "Signal",
  wg: "Skout",
  sf: "SneakersnStuff",
  mt: "Steam",
  vj: "Stormgain",
  lc: "Subito",
  wh: "TanTan",
  qd: "Taobao",
  ih: "TeenPattiStarpro",
  tg: "Telegram",
  qq: "Tencent QQ",
  lf: "TikTok/Douyin",
  gr_tl: "Tilda",
  oi: "Tinder",
  xd: "Tokopedia",
  bs: "TradeUP",
  gc: "TradingView",
  pr: "Trendyol",
  tl: "Truecaller",
  jt: "TurkiyePetrolleri",
  hb: "Twitch",
  tw: "Twitter",
  ub: "Uber",
  cp: "Uklon",
  hh: "Uplay",
  of: "Urent",
  yy: "Venmo",
  vi: "Viber",
  kc: "Vinted",
  sc: "Voggt",
  wb: "WeChat",
  kf: "Weibo",
  wa: "Whatsapp",
  qj: "Whoosh",
  uu: "Wildberries",
  mp: "Winmasters",
  rr: "Wolt",
  bd: "X5ID",
  mb: "Yahoo",
  yl: "Yalla",
  yi: "Yemeksepeti",
  mj: "Zalo",
  mz: "Zolushka",
  dy: "Zomato",
  mi: "Zupee",
  yd: "米画师Mihuashi",
  st: "Ашан (Ashan)",
  nb: "Верный (Vernyy)",
  vk: "Вконтакте (Vk.com, Vkontakte)",
  sh: "ВкусВилл (VkusVill)",
  we: "ДругВокруг (DrugVokrug)",
  ot: "Другой (Any Other)",
  gr_lt: "Лента (Lenta)",
  mg: "Магнит (Magnit)",
  ok: "Одноклассники (OK.ru, Odnoklassniki)",
  jr: "Самокат (Samokat)",
  xj: "СберМаркет (SberMarket)",
  be: "СберМегаМаркет (SberMegaMarket)",
  gr_sber: "СберЧаевые (SberChayevye)",
  yk: "СпортМастер (SportMaster)",
  ym: "Юла (Yula)",
  ya: "Яндекс (Yandex)",
};
